# Application
spring:
  application:
    name: accountservice

  # MySQL Database
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb?useSSL=false&serverTimezone=UTC
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA/Hibernate
  jpa:
    # database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    # show-sql: false
    # properties:
    #   hibernate:
    #     format_sql: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Producer Performance & Stability
      # acks: all
      # retries: 3
      # batch-size: 16384
      # linger-ms: 10
      # buffer-memory: 33554432
      properties:
        # Connection & Reconnection Settings
        # reconnect.backoff.ms: 50
        # reconnect.backoff.max.ms: 1000
        # metadata.max.age.ms: 300000

        # Timeouts
        request.timeout.ms: 30000
        connections.max.idle.ms: 540000
    topic:
      name: account-data-topic

server:
  port: 8080

# Logging
# logging:
#   level:
#     root: INFO
#     com:
#       account: DEBUG
#     org:
#       hibernate:
#         SQL: DEBUG
#   file:
#     name: logs/account-service.log
